### ISSUE TITLE
Improve the game

### ISSUE THREAD

**Issue by nasivuela** [Adalab/f-m2-evaluacion-intermedia-carmen-tm#1]
Beautifully done @carmen-tm !!

Here you have some tips to improve the exercise:

- [x] Remove ';' from the end of function blocks.
- [x] Clean the code, remove logs and commented code.
- [x] You are writing many times "gameTipsEl.innerHTML = 'something';", what about making a function that accepts a string as param and paints it into 'gameTipsEl'?
- [x] Move variables and constants declarations to the top of the file
- [x] Improve function 'countUserTrials'. It is declared into the handler, it means each time the user clicks the button, you are creating the function again. Also, you are parsing to integer the number 1. It is already an integer!
- [x] Define a good structure of folders and files for the project

Then you can improve the game as you please, here you have some ideas:

- Add new feedback when the number is bigger than 100 or smaller than 0.
- Manage when the user hits the button and the input is empty.
- Add a reset button that cleans the input, the counter, writes the initial feedback and generates a new random number to play again!
- Whatever you want!

Let me know if you have any doubts ;)

Go for it!!

**Comment by carmen-tm** [comment]
Hi @nasivuela, thanks for the feedback! The minimum fixes are done and integrated on current version v1.0. Now comes the funny part with more improvements and a nicer interface :) Will let u know if having doubts or a brand new release! Thankss :)

**Comment by nasivuela** [comment]
Cool @carmen-tm !!!

I'm closing this because it is a well-done work, but here you have some final tips!

On 'gameTips' function in each condition you are doing something like this:

```
const message = "HAS GANADO CAMPEONAA!!";
return paintGameTips(message);
```

I see two ways to improve it:

1. Just return simple paintGameTips
`return paintGameTips("HAS GANADO CAMPEONAA!!"');`

2. At the top of your document, declare a constant with all the feedback messages

```
const feedbackMessages = {
  win: "HAS GANADO CAMPEONAA!!",
  toHigh "Demasiado alto...",
  ...
}
```

and use it on 'gameTips' :
`return paintGameTips(feedbackMessages.win);`

Also, you have some simple functions like 'paintGameTips'. if you remove the log, you can convert it to a one-line arrow function and practice them.

Once you finish your game do not forget to clean erasing logs and comments.

![](https://media.giphy.com/media/l2Sq5GffrCyUMEXjW/giphy.gif)

**Comment by carmen-tm** [comment]
@nasivuela thankss again! I love the second idea, creating a message object with different properties :):)
